"""add original_filename to chat_messages

Revision ID: da4b3feeb1be
Revises: 0ea0cc60f19e
Create Date: 2026-07-16 17:32:35.628296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da4b3feeb1be'
down_revision: Union[str, Sequence[str], None] = '0ea0cc60f19e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('original_filename', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'original_filename')
    # ### end Alembic commands ###
